module.exports = {
  facebook: {
    FACEBOOK_APP_ID: 'YOUR_FACEBOOK_APP_ID',
    FACEBOOK_APP_SECRET: 'YOUR_FACEBOOK_APP_SECRET'
  },
  aws: {
    AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID",
    AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY",
    AWS_REGION: "AWS_REGION"
  }
};
